"""
Tests for the real e-Smart 'Daily Summary Report' parser and the biometric
week-off trust logic. The sample below mirrors the exact format of the client's
machine export (date section headers, wrapped names, WO/WOP/½P/(SE) statuses).
"""
import pandas as pd

from modules import biometric_parser as bp
from modules import processing
from modules import salary_engine as eng

ESMART_SAMPLE = """Department:- DefaultDepartment
Attendance Date - 01-May-2026
S.No Employee Code Employee Name Shift In Time Out Time Total Duration Status Remarks
1 1 SACHIN GS 10:26:25 21:46:16 11:20 P
2 27 BM GS 11:05:34 21:22:32 10:17 P
3 4 VINOD 4 NA 00:00 00:00 00:00 A
4 46 VIPIN JI GS 10:27:35 10:28:35(SE) 00:01 ½P
5 171 DEEPAK KUMAR
(DK
GS 10:28:55 21:21:39 10:53 P
Generated By:-smart Page 1 of 74
Daily Summary Report
01-May-2026 To 31-May-2026
Attendance Date - 04-May-2026
S.No Employee Code Employee Name Shift In Time Out Time Total Duration Status Remarks
1 1 SACHIN GS 11:26:31 21:41:16 10:15 WOP
2 27 BM GS 11:28:24 21:25:59 09:58 WOP
3 37 PK WO 00:00 00:00 00:00 WO
4 302 NIRANJAN GS 10:44:47 10:45:47(SE) 00:01 ½P(WO)
"""


def _parse():
    return bp.parse_esmart(ESMART_SAMPLE, source_location="KAMLA NAGAR")


def test_esmart_row_count_and_dates():
    rows, warns = _parse()
    # 5 rows on 01-May + 4 rows on 04-May = 9
    assert len(rows) == 9, [r["Emp_Code"] for r in rows]
    d1 = [r for r in rows if r["Emp_Code"] == "1"]
    assert {r["Attendance_Date"] for r in d1} == {"01/05/2026", "04/05/2026"}
    assert all(r["Month_Year"] == "05-2026" for r in rows)


def test_esmart_present_and_absent():
    rows, _ = _parse()
    by = {(r["Emp_Code"], r["Attendance_Date"]): r for r in rows}
    bm = by[("27", "01/05/2026")]
    assert bm["In_Time"] == "11:05:34" and bm["Status_Raw"] == "P"
    vinod = by[("4", "01/05/2026")]
    assert vinod["Status_Raw"] == "A" and vinod["In_Time"] == "" and vinod["Total_Duration_Mins"] == 0


def test_esmart_single_entry_flag():
    rows, _ = _parse()
    by = {(r["Emp_Code"], r["Attendance_Date"]): r for r in rows}
    vipin = by[("46", "01/05/2026")]
    assert vipin["Single_Entry_Flag"] == "TRUE"
    assert vipin["Total_Duration_Mins"] == 1


def test_esmart_wrapped_name():
    rows, _ = _parse()
    by = {(r["Emp_Code"], r["Attendance_Date"]): r for r in rows}
    dk = by[("171", "01/05/2026")]
    assert "DEEPAK KUMAR" in dk["Emp_Name"]
    assert dk["In_Time"] == "10:28:55" and dk["Status_Raw"] == "P"


def test_esmart_weekoff_statuses():
    rows, _ = _parse()
    by = {(r["Emp_Code"], r["Attendance_Date"]): r for r in rows}
    assert by[("1", "04/05/2026")]["Status_Raw"] == "WOP"
    assert by[("37", "04/05/2026")]["Status_Raw"] == "WO"
    assert by[("302", "04/05/2026")]["Single_Entry_Flag"] == "TRUE"  # ½P(WO)


def test_engine_trusts_biometric_weekoff():
    """A WOP day -> EXTRA_PRESENT; a WO day -> WEEK_OFF, regardless of weekday."""
    rows, _ = _parse()
    bio = pd.DataFrame(rows)
    overrides = pd.DataFrame(columns=["Emp_Code", "Override_Type", "Override_Date",
                                      "Override_Date_End", "New_Week_Off_Day", "Is_Active"])
    emp_bm = {"Emp_Code": "27", "Emp_Name": "BM", "Gender": "Male", "Shift_Exception": "None",
              "Base_Salary": 22000, "Week_Off_Default": "MON"}
    days = processing.process_employee_month(emp_bm, "05-2026", bio, overrides, set())
    by_date = {d.attendance_date: d for d in days}
    assert by_date["01/05/2026"].final_status == "PRESENT"
    assert by_date["04/05/2026"].final_status == "EXTRA_PRESENT"   # WOP honoured

    emp_pk = {"Emp_Code": "37", "Emp_Name": "PK", "Gender": "Male", "Shift_Exception": "None",
              "Base_Salary": 20500, "Week_Off_Default": "MON"}
    days_pk = processing.process_employee_month(emp_pk, "05-2026", bio, overrides, set())
    by_pk = {d.attendance_date: d for d in days_pk}
    assert by_pk["04/05/2026"].final_status == "WEEK_OFF"          # WO honoured
